### PR TITLE
Fix #133 : Set correct hostname for localhost

### LINKED ISSUE #133: Recaptcha validation fails everytime on form submit
Hi,

I am on the latest build of OctoberCMS and I have added the appropriate key and secret for reCaptcha v2 (checkbox).

The "I am not a robot" captcha is correctly displayed on the form and I can check it, but when I submit the form I get the default captcha validation error message (default : "Google reCAPTCHA validation error!")

Not sure if I'm doing something wrong!

Regards

### PR DESCRIPTION
**Pull request by kavishdahekar**
Fixes #133 
ReCaptcha validation's `setExpectedHostname` should use `localhost` instead of `127.0.0.1`

### CODE REVIEW

File: components/SmallContactForm.php [hunk 1]
```diff
@@ -357,7 +359,7 @@ public function onFormSend(){
               $recaptcha = new ReCaptcha(Settings::get('google_recaptcha_secret_key'));
             }
 
-            $response = $recaptcha->setExpectedHostname($_SERVER['SERVER_NAME'])->verify(post('g-recaptcha-response'), $_SERVER['REMOTE_ADDR']);
+            $response = $recaptcha->setExpectedHostname($this->validationReCaptchaServerName)->verify(post('g-recaptcha-response'), $_SERVER['REMOTE_ADDR']);
```
Comment (kavishdahekar) [inline components/SmallContactForm.php:362]: This could have been more compact like
```
$response = $recaptcha->setExpectedHostname($_SERVER['SERVER_NAME'] == "127.0.0.1" ? "localhost" : $_SERVER['SERVER_NAME'])->verify(post('g-recaptcha-response'), $_SERVER['REMOTE_ADDR']);
```
but would have looked messy.

**Comment by jan-vince** [comment]
Thank you!
